apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-3q7a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-3q7a
    app.kubernetes.io/part-of: ci10t-777-0078-app
  name: devfile-sample-3q7a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-3q7a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-3q7a
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0078-tenant/ci10t-777-0078-app/devfile-sample-3q7a@sha256:60342231dd58356ddf6e72c6e22ca22834c77f7255a42e8ce09a4e40491cb75f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
